# This file should be named mail.yml, in the same folder as this

host: "localhost"
smtp:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  username: "<username">
  password: "<password>>"
